# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Place.destroy_all
p1 = Place.create name:'Sydney', state: 'NSW', description: "Discover all the great Sydney attractions, from the sublime Sydney Harbour Bridge and the iconic Manly Beach to the marvellous Taronga Zoo, magnificent national parks, extraordinary heritage and much more. You’ll find many memorable things to do and fascinating places to visit in Sydney, Australia.", image:'https://www.pht.com.au/files/330_paustralia_014.jpg'
p2 = Place.create name:'Melbourne', state: 'VIC', description: "Melbourne is packed with attractions, from laid-back laneways and lush parks to grand libraries and museums, all wrapped up in a vibrant atmosphere.", image:'https://www.navigator.ro/uploads/images/2014/12/18/3-9aui.jpg'
p3 = Place.create name:'Canberra', state: 'ACT', description: "Canberra offers a great diversity of attractions and experiences all within close proximity to accommodation and transport. For solo travellers, couples, families and groups, Canberra has something to appeal to the curious, adventurous, foodie or explorer within us all.", image:'https://www.sbs.com.au/comedy/sites/sbs.com.au.comedy/files/styles/full/public/ec3aa931-576a-4309-8a09-d3c199059fe8.jpeg?itok=PPWznw8T&mtime=1471303398'
p4 = Place.create name:'Perth', state: 'WA', description: "Perth is a perfect base for exploring the region and making day trips to the wonderful surrounding areas.Things to do in Perth range from sightseeing, encountering wildlife, learning about Aboriginal culture, to having aquatic fun and desert adventures. Perth attractions and activities are sure to provide something for everyone during their stay in this sunniest capital of Western Australia.", image:'https://www.firsthomebuyersdirect.com.au/getattachment/d2eb0f23-30bd-4a45-9fdd-a552f030bdb3/Why-build-in-Perth-Now.aspx'
p5 = Place.create name:'Gold Coast', state: 'Queensland', description: "Known for being the city on the beach with truly epic theme parks, the Gold Coast and its surrounding area has plenty to see and do for the whole family.", image:'https://www.brisbanekids.com.au/wp-content/uploads/2016/03/gc1-001.jpg'
p6 = Place.create name:'Nelson Bay', state: 'NSW', description: "Nelson Bay is the main town for Port Stephens and it would be hard to find anywhere better equipped for aquatic pursuits, plus a great array of accommodation and dining options. On the town's doorstep within the sheltered arms of the bay there are safe, calm beaches that are ideal for small children, while the coastal beaches just a five-minute drive away are washed by booming waves.", image:'https://nnimgt-a.akamaihd.net/transform/v1/crop/frm/SKsbYhSeHQG3gsfDwZW5nX/9012f7f2-9e0d-4506-b3e2-df8231794f35.jpg/r0_302_2953_1969_w1200_h678_fmax.jpg'
p7 = Place.create name:'Wollongong', state: 'NSW', description: "Memorable adventures begin in Wollongong, a beautiful seaside destination perfect for day trips, weekend escapes and longer sojourns. NSW’s third-largest city is within easy reach from Sydney and home to stunning beaches, exciting water sports, thrilling skydiving and extensive cycleways.", image:'http://www.ocean6.events/wp-content/uploads/2017/09/Crop-Wollongong.jpg'
p8 = Place.create name:'Blue Mountains', state: 'NSW', description: "The Blue Mountains is a magical place any time of the year. Glowing in autumn, cool in winter, colourful in spring and refreshing in summer. The Blue Mountains is densely populated by oil bearing Eucalyptus trees. The atmosphere is filled with finely dispersed droplets of oil, which, in combination with dust particles and water vapour, scatter short-wave length rays of light which are predominantly blue in colour.", image:'https://cdn.experienceoz.com.au/assets/organisation/5914/banner/64709.jpg'
p9 = Place.create name:'Adelaide', state: 'SA', description: "Adelaide combines exceptional food and wine, art, shopping, a bustling bar scene and world-class events. We’ve also been award as a great wine capital of the world. No matter what season you visit, Adelaide and its regions allow you to sample the best of Australia.", image:'https://aestheticlasercourses.com/wp-content/uploads/2018/01/adelaide-Laser-Course.jpg'
p10 = Place.create name:'Queensland', state: 'Queensland', description: "Queensland, the Sunshine State, is Australia's most popular holiday destination. Golden beaches, reef-fringed tropical islands, fantastic surf breaks, World Heritage-listed rainforests, rivers, reefs, and waterfalls are just some of Queensland's natural jewels. And all of these sun-soaked settings offer a multitude of outdoor adventures. The dazzling Whitsunday Islands and the Great Barrier Reef offer superb diving and snorkeling. ", image:'https://www.myqldholiday.com.au/wp-content/uploads/sites/21/2017/08/My-QLD-900x600-Tropical-NQ.jpg'
p11 = Place.create name:'Brisbane', state: 'Queensland', description: "There is no shortage of major attractions to visit and explore in Brisbane. Across the river from the CBD, South Bank is home to our Cultural Centre with the world-class galleries and entertainment. Besides the big cultural attractions, Brisbane has two major sports stadiums, Lone Pine Koala Sanctuary and the Story Bridge to climb.", image:'https://www.calibrerealestate.com.au/wp-content/uploads/2015/01/Brisbane-Skyline.jpg'

Attraction.destroy_all
a1 = Attraction.create name:'Harbour Bridge', image: 'https://i0.wp.com/www.rumahtogel.net/wp-content/uploads/2018/01/sydney7638.jpg?w=1120', category: 'A Climb To Harbour Bridge', booking_link: 'https://www.bridgeclimb.com/'
a2 = Attraction.create name:'Luna park', image: 'https://vignette.wikia.nocookie.net/justdance/images/6/6e/Luna-park-sydney.jpg/revision/latest?cb=20161001041451', category: 'Take Rides With Family', booking_link: 'https://www.lunaparksydney.com/'
a3 = Attraction.create name:'Queen Victoria Building', image: 'https://fastrackcms-cambridgehotel.imgix.net/4962c4aeb1d29bc826799c5078a892b5/569d7937d1cd83.61924319.jpg?auto=format&fit=crop&ixlib=php-1.1.0&w=1600&s=750f3730b71e18f64249b1fc069314d0', category: 'Attraction to see', booking_link: 'https://www.sydney.com/destinations/sydney/sydney-city/city-centre/attractions/queen-victoria-building?utm_campaign-3dsydney-2520shopping=&%3Butm_content-3dvictoria-2520market=Sydney.comSydney.comSydney.com&%3Butm_medium-3dcpc=&%3Butm_term-3dvictoria-2520market-25201=Sydney.comSydney.comSydney.com&gclid=EAIaIQobChMI-OX93YiY2wIVDA4rCh1ZTAi_EAAYASAAEgL00PD_BwE&gclsrc=aw.ds'
a4 = Attraction.create name:'Split to Manly Walk', image: 'http://rosecoloredmoments.com/wp-content/uploads/2016/08/spit-to-manly-1080x725.jpg', category: 'A Walk from Split to Manly', booking_link: 'https://www.sydneycoastwalks.com.au/spit-to-manly-walk/'
a5 = Attraction.create name:'Toronga Zoo', image: 'https://taronga.org.au/sites/tarongazoo/files/styles/original/public/images/20151119-kangaroo-encounter.jpg?itok=NrlAdSPG&timestamp=1447897945', category: 'Explore the Toronga Zoo', booking_link: 'https://www.getyourguide.com/-l3734/?cmp=ga&campaign_id=471279976&adgroup_id=28583908216&target_id=aud-361607022877:kwd-1006247326&loc_physical_ms=9071791&match_type=e&ad_id=264983631308&keyword=taronga%20zoo&ad_position=1t2&feed_item_id=&placement=&partner_id=CD951&gclid=EAIaIQobChMIyMXemomY2wIVhwsrCh2Tvgh4EAAYAiAAEgLov_D_BwE'
a6 = Attraction.create name:'Royal Botanic Garden', image: 'http://www.wattersbrothers.com/wp-content/uploads/2018/01/Lovely-Royal-Botanic-Gardens-34-On-Excellent-Home-Design-Wallpaper-with-Royal-Botanic-Gardens.jpg', category: 'Travel through diversity of plentiful flowers. ', booking_link: 'https://www.rbgsyd.nsw.gov.au/visit/things-to-see-do'
a7 = Attraction.create name:'The Great Ocean Road', image: 'http://www.tourstogo.com.au/images/photos/zoomed/3e755118.jpg', category: 'A long Drive', booking_link: 'https://www.expedia.com.au/things-to-do/search?location=Great-Ocean-Road&regionId=6135588&semcid=AU.MULTILOB.GOOGLE.DL-c-EN.TSHOP&semdtl=a1381144974.b142444745192.r1.g1kwd-308031768475.i1.d1267849145588.e1c.j19071791.k1.f11t3.n1.l1g.h1b.m1&gclid=EAIaIQobChMImcH11ImY2wIVkDUrCh2FGgkDEAAYAyAAEgJk3vD_BwE'
a8 = Attraction.create name:'Phillip Island', image: 'https://www.iheartmelbournetours.com.au/wp-content/uploads/2014/08/phillip-island-penguins-feature.jpg', category: 'Phillip Island Penguin tour', booking_link: 'https://www.visitacity.com/en/phillip-island/activities/all-activities?activitiesSearchByName=tour&sbn_sec=tour&campaignid=304083845&gclid=EAIaIQobChMIoPqV64mY2wIVRyUrCh0-7QkWEAAYAyAAEgIvofD_BwE'
a9 = Attraction.create name:'Phillip Island Chocolate Factory', image: 'http://megafun.com.au/wp-content/uploads/2014/05/PAWC-Trainset-01.jpg', category: 'A Tour to Chocolate Factory', booking_link: 'https://phillipislandchocolatefactory.com.au/'
a10 = Attraction.create name:'Puffing Billy Tour', image: 'http://cd.visitmelbourne.com/-/media/atdw/yarra-valley-and-dandenong-ranges/things-to-do/history-and-heritage/478299b5387091b5f69c20f8eac1ac12_2048x1152.jpeg?ts=20171003330331&amp;cp=95', category: 'A Puffy Train Tour', booking_link: 'http://www.grayline.com.au/australia-sightseeing/melbourne-day-tours/puffing-billy-steam-train-tours'
a11 = Attraction.create name:'Parliament House', image: 'https://www.planetware.com/photos-large/AUS/australia-canberra-new-parliament-house.jpg', category: 'A Tour to Parliament House', booking_link: 'https://visitcanberra.com.au/attractions/56b23afa266140594567dc94/parliament-house'
a12 = Attraction.create name:'Lake Burley Griffin', image: 'https://www.planetware.com/photos-large/AUS/australia-canberra-lake-burley-griffin.jpg', category: 'Look Out At Lake Burley Griffin', booking_link: 'https://visitcanberra.com.au/attractions/56b23b58d5f1565045d801cf/lake-burley-griffin'
a13 = Attraction.create name:'National Museum of Australia', image: 'https://www.planetware.com/photos-large/AUS/australia-canberra-museum-of-australian-democracy-at-old-parliament-house.jpg', category: 'Take A Tour To National Museum', booking_link: 'https://visitcanberra.com.au/attractions/56b23afad5f1565045d7fc53/national-museum-of-australia'
a14 = Attraction.create name:'Black Mountain Nature Park', image: 'https://www.planetware.com/photos-large/AUS/australia-canberra-black-mountain-nature-park.jpg', category: 'Park Lookout', booking_link: 'https://www.inspirock.com/australia/canberra/black-mountain-nature-park-a322495697?gclid=EAIaIQobChMI96n3hIyY2wIVgwsrCh3S-gCCEAAYBCAAEgIYBfD_BwE'
a15 = Attraction.create name:'Mount Ainslie Lookout', image: 'https://www.planetware.com/photos-large/AUS/australia-canberra-mount-ainslie.jpg', category: 'Lookout At Mount Ainslie', booking_link: 'https://www.familytravel.com.au/attractions/things-to-do-with-kids-and-families-australia-mount-ainslie-lookout'
a16 = Attraction.create name:'Kings Park', image: 'https://98five.com/wp-content/uploads/2015/09/Kings-Park-4.jpg', category: 'A Tour to Kings Park'
a17 = Attraction.create name:'Swan Valley', image: 'https://www.vinodiversity.com/images/swanvalley.jpg', category: 'An excursion to Swan Valley'
a18 = Attraction.create name:'Swan Bells', image: 'https://thumbnails.trvl-media.com/pKwmdiudEHdOk3aaB4SnW-2bUgg=/768x432/images.trvl-media.com/media/content/shared/images/travelguides/destination/180013/Swan-Bells-Bell-Tower-40109.jpg', category: 'Lookout at Swan Bells'
a19 = Attraction.create name:'Surfing in Gold Coast', image: 'https://i0.wp.com/travelthefire.com/wp-content/uploads/2016/10/fiji-surf.jpg?zoom=2&resize=770%2C500&ssl=1', category: 'Surfing', booking_link: 'https://www.getyourguide.com/surfers-paradise-l998/surfers-paradise-2-hour-surf-lesson-on-the-gold-coast-t118180/?campaign_id=471293536&adgroup_id=30002583496&target_id=aud-361607022877:dsa-186708298169&loc_physical_ms=9071789&match_type=b&ad_id=266295393287&keyword=&ad_position=1t3&feed_item_id=&placement=&partner_id=CD951&gclid=EAIaIQobChMIhpmQgp2Z2wIVEiQrCh3hawMDEAAYAyAAEgJarfD_BwE'
a20 = Attraction.create name:'Canyon Flyer', image: 'https://www.treetopchallenge.com.au/images/canyonflyer/9-unleash-your-adrenalin.jpg', category: 'A fun with Canyon Flyer', booking_link: 'https://www.treetopchallenge.com.au/canyonflyer.aspx?gclid=EAIaIQobChMIkf6tsZ6Z2wIVEA4rCh1QrQjjEAAYAiAAEgIDJfD_BwE'
a21 = Attraction.create name:'Tandem Skydive', image: 'http://georgiesgetaway.com.au/assets/Products/Product-723/4e0be948e7272_426_sky-diving-037-cms.jpg?385a718e91a3f78213ac62d9dcb11996', category: 'A fun with Tandem Skydive', booking_link: 'https://www.ramblers.com.au/?ver=3.1&eid=315-46751-9&did=9&pub=315&gid=1017550&ctn=61754231159&ck=07243acd4fe0945d7ff7ef56c630ac6a&nw=g&kw=%2Btandem%20%2Bskydiving%20%2Bgold%20%2Bcoast&mt=b&cr=251280288916'
a22 = Attraction.create name:'Whale Watching', image: 'http://gemilangtravel.com.my/wp-content/uploads/2014/01/gold-cost.jpg', category: 'Whale Watching', booking_link: 'http://whalesinparadise.com.au/gold-coast/'
a23 = Attraction.create name:'Pacific Drive', image: 'https://www.visitnsw.com/sites/visitnsw/files/styles/gallery_no_thumb_large/public/2018-04/D1-151099-AeiralofSeaCliffBridge-DeeKramerPhotography.jpg?itok=LRUvMAqI', category: 'A Pacific Drive', booking_link: 'https://www.visitnsw.com/things-to-do/drives-and-road-trips/grand-pacific-drive'
a24 = Attraction.create name:'Nan Tien Temple', image: 'http://ausvisionholding.com.au/wp-content/uploads/2015/07/nan_tien_temple_accommodation.jpg', category: 'A Visit to Temple', booking_link: 'https://www.visitnsw.com/destinations/south-coast/wollongong-and-surrounds/wollongong/attractions/nan-tien-temple'
a25 = Attraction.create name:'Wollongong To Thirroul Bike Track', image: 'http://d1z63sdk26aghx.cloudfront.net/visitwollongong.com.au/b35aff36cb2780038df349fa32d2e7c7-uploads-313-cycling_blue-mile-1.jpg', category: 'Cycling Tour', booking_link: 'https://www.tripadvisor.com.au/Attraction_Review-g255333-d6413135-Reviews-Wollongong_To_Thirroul_Bike_Track-Wollongong_New_South_Wales.html'
a26 = Attraction.create name:'The Australian Motorlife Museum', image: 'https://reflectionsholidayparks.com.au/wp-content/uploads/2017/11/8671bf2fcb12d0060359c87eb6b5fc57.jpeg', category: 'An Excursion to Museum', booking_link: 'https://motorlifemuseum.com/'
a27 = Attraction.create name:'The Victory Theater Antique Centre', image: 'https://assets.atdw-online.com.au/images/WLS_Land__DK72_9270210_ATDW_Large_Landscape__9270209_DK72__DSC1080_c590vxm.jpg?rect=0,14,310,233&w=800&h=600', category: 'Antique Centre', booking_link: 'https://www.visitnsw.com/destinations/blue-mountains/katoomba-area/blackheath/attractions/the-victory-theatre-antique-centre'
a28 = Attraction.create name:'A Darwin Walk', image: 'https://assets.atdw-online.com.au/images/49ae6397ee4a0534f91cd28107463b82.jpeg?rect=251,0,2048,1536&w=800&h=600', category: 'A Darwin Walk', booking_link: 'https://www.visitnsw.com/destinations/blue-mountains/katoomba-area/wentworth-falls/attractions/charles-darwin-walk'
a29 = Attraction.create name:'Adelaide Hills', image: 'https://images.ctfassets.net/niwziy2l9cvz/43KejXeXcI6sEOAGQEo0Mq/72d644f37e365dff3ff127a089b1de4d/adelaide-city-1112x630__6_.jpg', category: 'Lookout at Adelaide Hills', booking_link: 'https://www.getyourguide.com/-l203/?cmp=ga&campaign_id=471279976&adgroup_id=29737654816&target_id=aud-196325824409:kwd-2634716382&loc_physical_ms=9071789&match_type=e&ad_id=192221776967&keyword=adelaide%20attractions&ad_position=1t3&feed_item_id=&placement=&partner_id=CD951&gclid=EAIaIQobChMIqvrRp6eZ2wIVRSQrCh2lAwpvEAAYAyAAEgKJBvD_BwE'
a30 = Attraction.create name:'Barossa Valley', image: 'https://images.ctfassets.net/niwziy2l9cvz/4p87SV8FLa6QaygGoEWYKI/3181a8f1bfde6980fca3485f7c7577ed/adelaide-city-1112x630__8_.jpg', category: 'A tour to valley', booking_link: 'https://www.getyourguide.com/-l203/?cmp=ga&campaign_id=471279976&adgroup_id=29737654816&target_id=aud-196325824409:kwd-2634716382&loc_physical_ms=9071789&match_type=e&ad_id=192221776967&keyword=adelaide%20attractions&ad_position=1t3&feed_item_id=&placement=&partner_id=CD951&gclid=EAIaIQobChMIqvrRp6eZ2wIVRSQrCh2lAwpvEAAYAyAAEgKJBvD_BwE'
a31 = Attraction.create name:'Whitsunday Island', image: 'https://s1.at.atcdn.net/wp-content/uploads/2012/04/004.-Hill-Inlet-Whitsunday-island-QLD-Ken-Duncan.jpg', category: 'A tour to Whitsunday Island', booking_link: 'https://www.australiantraveller.com/qld/the-whitsundays/004-hill-inlet-whitsunday-island-qld/'
a32 = Attraction.create name:'Sea Life SunShine Coast', image: 'https://www.brisbanekids.com.au/wp-content/uploads/2016/12/IMG_3812.jpg', category: 'A tour to valley', booking_link: 'https://www.racq.com.au/membership/what-you-get/discounts/SEA-LIFE-Sunshine-Coast'
a33 = Attraction.create name:'Australia Zoo', image: 'https://holidaycorp.co.za/wp-content/uploads/2018/04/smaller.jpg', category: 'A tour to Australia Zoo', booking_link: 'https://www.getyourguide.com/brisbane-l300/australia-zoo-general-admission-ticket-t108640/?referrer_view_id=e65881d95f58f2b4cac0f233b873e039&referrer_view_position=4'
a34 = Attraction.create name:'Rainforest and Glow Worm Cave', image: 'https://media.nomadicmatt.com/waitomonz3.jpg', category: 'A tour to valley', booking_link: 'https://www.getyourguide.com/brisbane-l300/from-brisbane-rainforest-and-glow-worm-tour-t68262/?referrer_view_id=e65881d95f58f2b4cac0f233b873e039&referrer_view_position=5'

User.destroy_all
u1 = User.create name:'gurdeep', password:'deep'
u1 = User.create name:'harry', password:'deep'


Review.destroy_all
r1 = Review.create comment: 'very nice place to visit'
r2 = Review.create comment: 'very nice place to visit'
r3 = Review.create comment: 'very nice place to visit'

a1.reviews << r1 << r2 << r3


p1.attractions << a1 << a2 << a3 << a4 << a5 << a6
p2.attractions << a7 << a8 << a9 << a10
p3.attractions << a11 << a12 << a13 << a14 << a15
p4.attractions << a16 << a17 << a18
p5.attractions << a19 << a20 << a21 << a22
p6.attractions << a23 << a24
p7.attractions << a25 << a26
p8.attractions << a27 << a28
p9.attractions << a29 << a30
p10.attractions << a31 << a32
p11.attractions << a33 << a34
